/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ConnectorsRouteImport } from './routes/connectors'
import { Route as ComposerRouteImport } from './routes/composer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIndexRouteImport } from './routes/series.index'
import { Route as SeriesVideosRouteImport } from './routes/series.videos'
import { Route as SeriesSettingsRouteImport } from './routes/series.settings'
import { Route as SeriesCreateRouteImport } from './routes/series.create'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioGenerateRouteImport } from './routes/studio.generate'
import { Route as StudioAssetsRouteImport } from './routes/studio.assets'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRoute = ConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposerRoute = ComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesVideosRoute = SeriesVideosRouteImport.update({
  id: '/series/videos',
  path: '/series/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSettingsRoute = SeriesSettingsRouteImport.update({
  id: '/series/settings',
  path: '/series/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesCreateRoute = SeriesCreateRouteImport.update({
  id: '/series/create',
  path: '/series/create',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioGenerateRoute = StudioGenerateRouteImport.update({
  id: '/studio/generate',
  path: '/studio/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioAssetsRoute = StudioAssetsRouteImport.update({
  id: '/studio/assets',
  path: '/studio/assets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/composer': typeof ComposerRoute
  '/connectors': typeof ConnectorsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/series/create': typeof SeriesCreateRoute
  '/series/settings': typeof SeriesSettingsRoute
  '/series/videos': typeof SeriesVideosRoute
  '/series/': typeof SeriesIndexRoute
  '/studio/generate': typeof StudioGenerateRoute
  '/studio/assets': typeof StudioAssetsRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/composer': typeof ComposerRoute
  '/connectors': typeof ConnectorsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/series/create': typeof SeriesCreateRoute
  '/series/settings': typeof SeriesSettingsRoute
  '/series/videos': typeof SeriesVideosRoute
  '/series': typeof SeriesIndexRoute
  '/studio/generate': typeof StudioGenerateRoute
  '/studio/assets': typeof StudioAssetsRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/composer': typeof ComposerRoute
  '/connectors': typeof ConnectorsRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/series/create': typeof SeriesCreateRoute
  '/series/settings': typeof SeriesSettingsRoute
  '/series/videos': typeof SeriesVideosRoute
  '/series/': typeof SeriesIndexRoute
  '/studio/generate': typeof StudioGenerateRoute
  '/studio/assets': typeof StudioAssetsRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/composer'
    | '/connectors'
    | '/history'
    | '/login'
    | '/settings'
    | '/series/create'
    | '/series/settings'
    | '/series/videos'
    | '/series/'
    | '/studio/generate'
    | '/studio/assets'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/composer'
    | '/connectors'
    | '/history'
    | '/login'
    | '/settings'
    | '/series/create'
    | '/series/settings'
    | '/series/videos'
    | '/series'
    | '/studio/generate'
    | '/studio/assets'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/composer'
    | '/connectors'
    | '/history'
    | '/login'
    | '/settings'
    | '/series/create'
    | '/series/settings'
    | '/series/videos'
    | '/series/'
    | '/studio/generate'
    | '/studio/assets'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComposerRoute: typeof ComposerRoute
  ConnectorsRoute: typeof ConnectorsRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SeriesCreateRoute: typeof SeriesCreateRoute
  SeriesSettingsRoute: typeof SeriesSettingsRoute
  SeriesVideosRoute: typeof SeriesVideosRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  StudioGenerateRoute: typeof StudioGenerateRoute
  StudioAssetsRoute: typeof StudioAssetsRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composer': {
      id: '/composer'
      path: '/composer'
      fullPath: '/composer'
      preLoaderRoute: typeof ComposerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/videos': {
      id: '/series/videos'
      path: '/series/videos'
      fullPath: '/series/videos'
      preLoaderRoute: typeof SeriesVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/settings': {
      id: '/series/settings'
      path: '/series/settings'
      fullPath: '/series/settings'
      preLoaderRoute: typeof SeriesSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/create': {
      id: '/series/create'
      path: '/series/create'
      fullPath: '/series/create'
      preLoaderRoute: typeof SeriesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/generate': {
      id: '/studio/generate'
      path: '/studio/generate'
      fullPath: '/studio/generate'
      preLoaderRoute: typeof StudioGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/assets': {
      id: '/studio/assets'
      path: '/studio/assets'
      fullPath: '/studio/assets'
      preLoaderRoute: typeof StudioAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComposerRoute: ComposerRoute,
  ConnectorsRoute: ConnectorsRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SeriesCreateRoute: SeriesCreateRoute,
  SeriesSettingsRoute: SeriesSettingsRoute,
  SeriesVideosRoute: SeriesVideosRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  StudioGenerateRoute: StudioGenerateRoute,
  StudioAssetsRoute: StudioAssetsRoute,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
